auto: true
server: true
destination: ./_site
markdown: rdiscount
pygments: true
lsi: false
exclude: capfile, capistrano
permalink: /:categories/:title
domain: localhost:4000
url: http://localhost:4000
title: Your Site Title
googleverification: yourverificationcodehere
googleanalyticsid: UA-0000000-0
author: Author Name
authoremail: test@example.com
copyright: Your Company